In [2]:
import torch
import numpy as np

In [3]:
data = np.array([1,2,3], dtype=np.int32)

In [4]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [5]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [6]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [7]:
torch.get_default_dtype()

torch.float32

In [8]:
t2 = torch.tensor(data, dtype=torch.float64)
print(t2)

tensor([1., 2., 3.], dtype=torch.float64)


In [9]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [10]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [11]:
data[:] = 0
data

array([0, 0, 0])

In [12]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [20]:
print(t3)
print(t4)

tensor([2., 4., 6.])
tensor([0, 0, 0], dtype=torch.int32)
