In [1]:
# 1. Using qtorch to tensor

import torch
from qtorch.quant import Quantizer, quantizer
from qtorch import FloatingPoint

In [2]:
random_input = torch.rand([3,3])
print(random_input)

tensor([[0.5810, 0.0739, 0.7276],
        [0.1180, 0.7910, 0.5058],
        [0.5108, 0.6538, 0.4335]])


In [3]:
constant_input = torch.tensor([[255., -255.],[3.4, 3.6]])
print(constant_input)

tensor([[ 255.0000, -255.0000],
        [   3.4000,    3.6000]])


In [4]:
# Set quantizer
bit = FloatingPoint(exp=2, man=1)
quant = quantizer(forward_number=bit, forward_rounding="nearest")

In [5]:
random_output = quant(random_input)
print(random_output)

tensor([[0.5000, 0.0000, 0.7500],
        [0.0000, 0.7500, 0.5000],
        [0.5000, 0.7500, 0.5000]])


In [6]:
constant_output = quant(constant_input)
print(constant_output)

tensor([[ 3., -3.],
        [ 3.,  3.]])
